feat: Allow esbuild 0.24
pradel/esbuild-node-externals pull request #64
Opened 2024-09-23 19:02 UTC by danilofuchs

2024-09-23 19:20 UTC, pradel requested changes

2024-09-23 19:20 UTC, pradel commented on esbuild-node-externals/README.md
> +This plugin requires minimum **Node.js 18**, and **Esbuild 0.21+**.
why did you change the minimum esbuild version here? It's didn't change in the package.json and as there is no breaking changes in these releases for our plugin it should be fine no?

2024-09-26 08:31 UTC, antongolub commented
Hmm... I think, if the plugin is still still [compatible with esbuild@0.12.x](https://github.com/pradel/esbuild-node-externals/pull/65/checks#step:9:47), we have no reason to restrict nodejs version.

2024-09-26 17:31 UTC, danilofuchs commented
> Hmm... I think, if the plugin is still still [compatible with esbuild@0.12.x](https://github.com/pradel/esbuild-node-externals/pull/65/checks#step:9:47), we have no reason to restrict nodejs version.

My mistake! I wrongly read `esbuild 0.21 - 0.23` instead of `esbuild 0.12 - 0.23` in the package.json and assumed the minimum node version was out of date

2024-09-26 17:33 UTC, danilofuchs commented
Closed in favour of https://github.com/pradel/esbuild-node-externals/pull/65

2024-09-26 17:33 UTC, closed without merging